import os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

base = os.environ["EQUIPE_TESTE_BASE"]
slug = os.environ["EQUIPE_TESTE_SLUG"]
token = os.environ["EQUIPE_TESTE_TOKEN"]

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=True)
    context = browser.new_context(viewport={"width": 1280, "height": 900})
    context.route("**/api/refresh", lambda route: route.fulfill(status=200, json={"token": token, "slug": slug, "nome": "Restaurante teste"}))
    context.route("https://js.stripe.com/**", lambda route: route.fulfill(status=200, body=""))
    page = context.new_page()
    page.goto(base + "/admin.html")
    page.locator('nav button[data-aba="equipe"]').click()
    page.locator("#equipeAdicionar").click()
    page.locator("#equipeNome").fill("Caixa da homologação")
    page.locator("#equipeFuncionarioPin").fill("7531")
    page.locator("#equipeSalvar").click()
    expect(page.locator("#equipeGaveta")).to_be_hidden()
    expect(page.locator("#equipeLista")).to_contain_text("Caixa da homologação")
    page.locator("#equipeDispositivoNome").fill("Balcão de teste")
    page.locator("#equipeAutorizarDispositivo").click()
    expect(page.locator("#equipeDispositivosLista")).to_contain_text("Balcão de teste")
    page.locator("#btnTrocarOperador").click()
    page.locator("#equipePin").fill("7531")
    page.locator('#equipeOperadorForm button[type="submit"]').click()
    expect(page.locator("#headerNome")).to_have_text("Caixa da homologação")
    expect(page.locator('nav button[data-aba="equipe"]')).to_be_hidden()
    expect(page.locator('nav button[data-aba="pedidos"]').first).to_be_visible()
    status = page.evaluate("""async () => {
      const sessao = JSON.parse(sessionStorage.getItem('equipeSessao'));
      return (await fetch('/api/assinatura', {headers: {Authorization: 'Bearer ' + sessao.token}})).status;
    }""")
    assert status == 403
    dono = page.context.new_page()
    dono.goto(base + "/admin.html")
    dono.locator('nav button[data-aba="equipe"]').click()
    dono.locator(".equipe-dispositivo button").filter(has_text="Revogar").click()
    dono.locator("#modal-confirmar").click()
    expect(dono.locator(".equipe-dispositivo")).to_have_count(0)
    dono.locator('nav button[data-aba="atividades"]').click()
    dono.locator("#atividadesEvento").select_option("dispositivo_revogado")
    dono.locator('#atividadesFiltros button[type="submit"]').click()
    expect(dono.locator("#atividadesLista")).to_contain_text("Dispositivo revogado")
    dono.locator("#atividadesLista button").first.click()
    expect(dono.locator("#atividadesDetalhe")).to_be_visible()
    dono.keyboard.press("Escape")
    expect(dono.locator("#atividadesDetalhe")).to_be_hidden()
    page.evaluate("api('GET', '/api/equipe/principal')")
    expect(page).to_have_url(base + "/admin.html?operador=" + slug)
    expect(page.locator("#equipeOperadorModal")).to_be_visible()
    expect(page.locator("#equipeOperadorErro")).to_contain_text("autorize")
    dono.set_viewport_size({"width": 375, "height": 812})
    expect(dono.locator("#atividadesLista")).to_contain_text("Dispositivo revogado")
    assert dono.evaluate("document.documentElement.scrollWidth <= innerWidth")
    for seletor in ["#atividadesEvento", "#atividadesAtor", "#atividadesDesde", "#atividadesAte", "#atividadesLista button"]:
        caixa = dono.locator(seletor).first.bounding_box()
        assert caixa and caixa["height"] >= 44, seletor
    dono.locator("#atividadesLista button").first.click()
    expect(dono.locator("#atividadesDetalhe")).to_be_visible()
    dono.keyboard.press("Escape")
    expect(dono.locator("#atividadesDetalhe")).to_be_hidden()
    capturas = Path(__file__).resolve().parent / "resultados"
    capturas.mkdir(parents=True, exist_ok=True)
    dono.screenshot(path=str(capturas / "atividades-mobile.png"), full_page=True)
    dono.set_viewport_size({"width": 1280, "height": 900})
    dono.screenshot(path=str(capturas / "atividades-desktop.png"), full_page=True)
    dono.locator("#atividadesEvento").select_option("pin_bloqueado")
    dono.locator('#atividadesFiltros button[type="submit"]').click()
    expect(dono.locator("#atividadesVazio")).to_be_visible()
    dono.route("**/api/equipe/atividades?**", lambda route: route.fulfill(status=500, json={"erro": "Falha temporária de teste"}))
    dono.locator("#atividadesLimpar").click()
    expect(dono.locator("#atividadesErro")).to_be_visible()
    dono.unroute("**/api/equipe/atividades?**")
    dono.locator("#atividadesTentar").click()
    expect(dono.locator("#atividadesLista")).to_be_visible()
    expect(dono.locator("#atividadesLista .atividades-linha")).to_have_count(30)
    dono.locator("#atividadesMais").click()
    expect(dono.locator("#atividadesMais")).to_be_hidden()
    assert dono.locator("#atividadesLista .atividades-linha").count() > 35
    # Repetir o ciclo real em viewport mobile, sem depender da simulação de layout.
    dono.set_viewport_size({"width": 375, "height": 812})
    dono.locator("#btnMenuMobile").click()
    dono.locator('nav button[data-aba="equipe"]').click()
    dono.locator("#equipeAdicionar").click()
    dono.locator("#equipeNome").fill("Operador mobile")
    dono.locator("#equipeFuncionarioPin").fill("7532")
    dono.locator("#equipeSalvar").click()
    expect(dono.locator("#equipeGaveta")).to_be_hidden()
    dono.locator("#equipeDispositivoNome").fill("Mobile de teste")
    dono.locator("#equipeAutorizarDispositivo").click()
    expect(dono.locator("#equipeDispositivosLista")).to_contain_text("Mobile de teste")
    dono.locator("#btnMenuMobile").click()
    dono.locator("#btnTrocarOperadorMobile").click()
    dono.locator("#equipeOperadorSelect").select_option(label="Operador mobile · Caixa")
    dono.locator("#equipePin").fill("7532")
    dono.locator('#equipeOperadorForm button[type="submit"]').click()
    expect(dono.locator("#headerNome")).to_have_text("Operador mobile")
    master = context.new_page()
    master.set_viewport_size({"width": 375, "height": 812})
    master.goto(base + "/admin.html")
    master.locator("#btnMenuMobile").click()
    master.locator('nav button[data-aba="equipe"]').click()
    master.locator(".equipe-dispositivo button").filter(has_text="Revogar").click()
    master.locator("#modal-confirmar").click()
    expect(master.locator(".equipe-dispositivo")).to_have_count(0)
    master.locator("[data-abrir-atividades]").click()
    master.locator("#atividadesEvento").select_option("dispositivo_revogado")
    master.locator('#atividadesFiltros button[type="submit"]').click()
    expect(master.locator("#atividadesLista .atividades-linha")).to_have_count(2)
    dono.evaluate("api('GET', '/api/equipe/principal')")
    expect(dono.locator("#equipeOperadorModal")).to_be_visible()
    assert dono.evaluate("sessionStorage.getItem('equipeSessao')") is None
    master.close()
    dono.close()
    # O ciclo de inatividade foi homologado em T-03.02; agora validamos revogação.
    page.clock.install()
    page.clock.fast_forward(16 * 60 * 1000)
    expect(page).to_have_url(base + "/admin.html?operador=" + slug)
    expect(page.locator("#equipeOperadorModal")).to_be_visible()
    assert page.evaluate("sessionStorage.getItem('equipeSessao')") is None
    browser.close()

print("OK: equipe/PIN, revogação interrompe operador, Atividades desktop/mobile, detalhes/Escape, vazio/erro/retry")
